### PR TITLE
Convert to v3 API, add tests

### PR DESCRIPTION
**Pull request by stephenyeargin**
This PR converts existing functionality to a API V3 client and adds test coverage.

---

**Note:** This also adds a workflow for releasing to NPM by running `npm run-script release`. This should make it easier to have release notes/etc. for released versions. [Documentation](https://github.com/webpro/release-it)

### CODE REVIEW

**Comment by m-baumgartner** [comment]
@stephenyeargin sure, should I just transfer you ownership of the repo? 
I'm really not using this anymore and don't have much time to participate in maintenance.

**Comment by stephenyeargin** [comment]
I think adding me as a maintainer on the `hubot-scripts` [team](https://github.com/orgs/hubot-scripts/teams/hubot-mailchimp) should work fine, and adding me to the [NPM package](https://www.npmjs.com/package/hubot-mailchimp) as a contributor.

_I'm assuming that team exists. That's the way other repos have been set up for me on this org._

**Comment by m-baumgartner** [comment]
The team looks like it exist but i can't add anyone for some reason.
I just added you to the collaborators list as well as a maintainer to the npm package as you requested. Tell me if anything is not correct.

**Comment by stephenyeargin** [comment]
Looks like everything's in place. I'll update some documentation and get a release cut.

**Comment by stephenyeargin** [comment]
Published as part of `v1.3.0`.

**Pull request merged**
